/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPodcastRouteImport } from './routes/_authenticated/podcast'
import { Route as AuthenticatedMusicRouteImport } from './routes/_authenticated/music'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedInternalRouteImport } from './routes/_authenticated/internal'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as AuthenticatedMangaIdRouteImport } from './routes/_authenticated/manga.$id'
import { Route as AuthenticatedMangaIdReadChapterIdRouteImport } from './routes/_authenticated/manga.$id.read.$chapterId'
import { Route as AuthenticatedMangaIdChapterChapterIdRouteImport } from './routes/_authenticated/manga.$id.chapter.$chapterId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPodcastRoute = AuthenticatedPodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMusicRoute = AuthenticatedMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInternalRoute = AuthenticatedInternalRouteImport.update({
  id: '/internal',
  path: '/internal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMangaIdRoute = AuthenticatedMangaIdRouteImport.update({
  id: '/manga/$id',
  path: '/manga/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMangaIdReadChapterIdRoute =
  AuthenticatedMangaIdReadChapterIdRouteImport.update({
    id: '/read/$chapterId',
    path: '/read/$chapterId',
    getParentRoute: () => AuthenticatedMangaIdRoute,
  } as any)
const AuthenticatedMangaIdChapterChapterIdRoute =
  AuthenticatedMangaIdChapterChapterIdRouteImport.update({
    id: '/chapter/$chapterId',
    path: '/chapter/$chapterId',
    getParentRoute: () => AuthenticatedMangaIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/about': typeof AuthenticatedAboutRoute
  '/account': typeof AuthenticatedAccountRoute
  '/home': typeof AuthenticatedHomeRoute
  '/internal': typeof AuthenticatedInternalRoute
  '/members': typeof AuthenticatedMembersRoute
  '/music': typeof AuthenticatedMusicRoute
  '/podcast': typeof AuthenticatedPodcastRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/manga/$id': typeof AuthenticatedMangaIdRouteWithChildren
  '/manga/$id/chapter/$chapterId': typeof AuthenticatedMangaIdChapterChapterIdRoute
  '/manga/$id/read/$chapterId': typeof AuthenticatedMangaIdReadChapterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/about': typeof AuthenticatedAboutRoute
  '/account': typeof AuthenticatedAccountRoute
  '/home': typeof AuthenticatedHomeRoute
  '/internal': typeof AuthenticatedInternalRoute
  '/members': typeof AuthenticatedMembersRoute
  '/music': typeof AuthenticatedMusicRoute
  '/podcast': typeof AuthenticatedPodcastRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/manga/$id': typeof AuthenticatedMangaIdRouteWithChildren
  '/manga/$id/chapter/$chapterId': typeof AuthenticatedMangaIdChapterChapterIdRoute
  '/manga/$id/read/$chapterId': typeof AuthenticatedMangaIdReadChapterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/internal': typeof AuthenticatedInternalRoute
  '/_authenticated/members': typeof AuthenticatedMembersRoute
  '/_authenticated/music': typeof AuthenticatedMusicRoute
  '/_authenticated/podcast': typeof AuthenticatedPodcastRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/_authenticated/manga/$id': typeof AuthenticatedMangaIdRouteWithChildren
  '/_authenticated/manga/$id/chapter/$chapterId': typeof AuthenticatedMangaIdChapterChapterIdRoute
  '/_authenticated/manga/$id/read/$chapterId': typeof AuthenticatedMangaIdReadChapterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/about'
    | '/account'
    | '/home'
    | '/internal'
    | '/members'
    | '/music'
    | '/podcast'
    | '/profile'
    | '/upload'
    | '/manga/$id'
    | '/manga/$id/chapter/$chapterId'
    | '/manga/$id/read/$chapterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/about'
    | '/account'
    | '/home'
    | '/internal'
    | '/members'
    | '/music'
    | '/podcast'
    | '/profile'
    | '/upload'
    | '/manga/$id'
    | '/manga/$id/chapter/$chapterId'
    | '/manga/$id/read/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/about'
    | '/_authenticated/account'
    | '/_authenticated/home'
    | '/_authenticated/internal'
    | '/_authenticated/members'
    | '/_authenticated/music'
    | '/_authenticated/podcast'
    | '/_authenticated/profile'
    | '/_authenticated/upload'
    | '/_authenticated/manga/$id'
    | '/_authenticated/manga/$id/chapter/$chapterId'
    | '/_authenticated/manga/$id/read/$chapterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/podcast': {
      id: '/_authenticated/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof AuthenticatedPodcastRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/music': {
      id: '/_authenticated/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof AuthenticatedMusicRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/internal': {
      id: '/_authenticated/internal'
      path: '/internal'
      fullPath: '/internal'
      preLoaderRoute: typeof AuthenticatedInternalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manga/$id': {
      id: '/_authenticated/manga/$id'
      path: '/manga/$id'
      fullPath: '/manga/$id'
      preLoaderRoute: typeof AuthenticatedMangaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manga/$id/read/$chapterId': {
      id: '/_authenticated/manga/$id/read/$chapterId'
      path: '/read/$chapterId'
      fullPath: '/manga/$id/read/$chapterId'
      preLoaderRoute: typeof AuthenticatedMangaIdReadChapterIdRouteImport
      parentRoute: typeof AuthenticatedMangaIdRoute
    }
    '/_authenticated/manga/$id/chapter/$chapterId': {
      id: '/_authenticated/manga/$id/chapter/$chapterId'
      path: '/chapter/$chapterId'
      fullPath: '/manga/$id/chapter/$chapterId'
      preLoaderRoute: typeof AuthenticatedMangaIdChapterChapterIdRouteImport
      parentRoute: typeof AuthenticatedMangaIdRoute
    }
  }
}

interface AuthenticatedMangaIdRouteChildren {
  AuthenticatedMangaIdChapterChapterIdRoute: typeof AuthenticatedMangaIdChapterChapterIdRoute
  AuthenticatedMangaIdReadChapterIdRoute: typeof AuthenticatedMangaIdReadChapterIdRoute
}

const AuthenticatedMangaIdRouteChildren: AuthenticatedMangaIdRouteChildren = {
  AuthenticatedMangaIdChapterChapterIdRoute:
    AuthenticatedMangaIdChapterChapterIdRoute,
  AuthenticatedMangaIdReadChapterIdRoute:
    AuthenticatedMangaIdReadChapterIdRoute,
}

const AuthenticatedMangaIdRouteWithChildren =
  AuthenticatedMangaIdRoute._addFileChildren(AuthenticatedMangaIdRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedInternalRoute: typeof AuthenticatedInternalRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRoute
  AuthenticatedMusicRoute: typeof AuthenticatedMusicRoute
  AuthenticatedPodcastRoute: typeof AuthenticatedPodcastRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedMangaIdRoute: typeof AuthenticatedMangaIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedInternalRoute: AuthenticatedInternalRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRoute,
  AuthenticatedMusicRoute: AuthenticatedMusicRoute,
  AuthenticatedPodcastRoute: AuthenticatedPodcastRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedMangaIdRoute: AuthenticatedMangaIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
